"""Mock for tests in development environement"""


mock_radio_stats = [
    {
        "BroadcastPacketsReceived" : 0,
        "BroadcastPacketsSent" : 0,
        "BytesReceived" : 888,
        "BytesSent" : 999,
        "DiscardPacketsReceived" : 0,
        "DiscardPacketsSent" : 0,
        "ErrorsReceived" : 0,
        "ErrorsSent" : 3,
        "FailedRetransCount" : 0,
        "MulticastPacketsReceived" : 0,
        "MulticastPacketsSent" : 0,
        "MultipleRetryCount" : 0,
        "Noise" : -90,
        "PacketsReceived" : 173,
        "PacketsSent" : 5520,
        "RetransCount" : 0,
        "RetryCount" : 0,
        "Temperature" : 39,
        "UnicastPacketsReceived" : 0,
        "UnicastPacketsSent" : 0,
        "UnknownProtoPacketsReceived" : 0,
        "WmmBytesReceived" : {
            "AC_BE" : 16981,
            "AC_BK" : 0,
            "AC_VI" : 0,
            "AC_VO" : 0
        },
        "WmmBytesSent" : {
            "AC_BE" : 1610251,
            "AC_BK" : 0,
            "AC_VI" : 704,
            "AC_VO" : 3142
        },
        "WmmFailedBytesReceived" : {
            "AC_BE" : 0,
            "AC_BK" : 0,
            "AC_VI" : 0,
            "AC_VO" : 0
        },
        "WmmFailedReceived" : {
            "AC_BE" : 0,
            "AC_BK" : 0,
            "AC_VI" : 0,
            "AC_VO" : 0
        },
        "WmmFailedSent" : {
            "AC_BE" : 4,
            "AC_BK" : 0,
            "AC_VI" : 0,
            "AC_VO" : 0
        },
        "WmmFailedbytesSent" : {
            "AC_BE" : 102,
            "AC_BK" : 0,
            "AC_VI" : 0,
            "AC_VO" : 0
        },
        "WmmPacketsReceived" : {
            "AC_BE" : 173,
            "AC_BK" : 0,
            "AC_VI" : 0,
            "AC_VO" : 0
        },
        "WmmPacketsSent" : {
            "AC_BE" : 5493,
            "AC_BK" : 0,
            "AC_VI" : 4,
            "AC_VO" : 23
        },
    }
]

mock_radio_stats_2 = [{key: value for key, value in mock_radio_stats[0].items()}]

mock_radio_air_stats = [
    {
        "FreeTime" : 53,
        "IntTime" : 38,
        "Load" : 47,
        "LongPreambleErrorPercentage" : 0,
        "Noise" : -90,
        "NoiseTime" : 31,
        "ObssTime" : 7,
        "RxTime" : 0,
        "ShortPreambleErrorPercentage" : 24,
        "Timestamp" : 3534848,
        "TotalTime" : 95,
        "TxTime" : 4,
        "VendorStats" : {
            "BadPlcp" : 21,
            "Glitch" : 9099
        }
    }
]

mock_stations = {
    "Device.WiFi.AccessPoint.1.AssociatedDevice.1.": {
        "Active": 1,
        "AssociationTime": "Tue, 28 Jan 2025 08:49:58 GMT",
        "AuthenticationState": 1,
        "AvgSignalStrength": 0,
        "AvgSignalStrengthByChain": -37,
        "Capabilities": "RRM,BTM,PMF",
        "ChargeableUserId": "",
        "ConnectionDuration": 22412,
        "DevicePriority": 1,
        "DeviceType": "Data",
        "DisassociationTime": "Tue, 28 Jan 2025 08:49:54 GMT",
        "DownlinkBandwidth": 80,
        "DownlinkMCS": 11,
        "DownlinkRateSpec": "he_11_80_2_1600",
        "DownlinkShortGuard": 1,
        "EncryptionMode": "Default",
        "FrequencyCapabilities": "2.4GHz,5GHz,6GHz",
        "HeCapabilities": "SU&MU-BFE",
        "HtCapabilities": "40MHz,SGI20,SGI40",
        "Inactive": 5,
        "LastDataDownlinkRate": 1134200,
        "LastDataUplinkRate": 1200900,
        "LastStateChange": "Tue, 28 Jan 2025 08:49:59 GMT",
        "LinkBandwidth": "80MHz",
        "MACAddress": "78:AF:08:31:B1:18",
        "MUGroupId": 0,
        "MUMimoTxPktsCount": 0,
        "MUMimoTxPktsPercentage": 0,
        "MUUserPositionId": 0,
        "MaxBandwidthSupported": "160MHz",
        "MaxDownlinkRateReached": 1200900,
        "MaxDownlinkRateSupported": 2401911,
        "MaxRxSpatialStreamsSupported": 2,
        "MaxTxSpatialStreamsSupported": 2,
        "MaxUplinkRateReached": 1200900,
        "MaxUplinkRateSupported": 2401911,
        "Noise": 86,
        "OperatingStandard": "ax",
        "PowerSave": 0,
        "Retransmissions": 0,
        "RrmCapabilities": "NEIGHBOR,BEACON_ACTIVE,BEACON_PASSIVE,BEACON_TABLE",
        "RrmOffChannelMaxDuration": 0,
        "RrmOnChannelMaxDuration": 0,
        "RxBytes": 1972163,
        "RxMulticastPacketCount": 0,
        "RxPacketCount": 15135,
        "RxSupportedHe160MCS": "11,11",
        "RxSupportedHe80x80MCS": "",
        "RxSupportedHeMCS": "11,11",
        "RxSupportedVhtMCS": "9,9",
        "RxUnicastPacketCount": 0,
        "Rx_Retransmissions": 0,
        "Rx_RetransmissionsFailed": 0,
        "SecurityModeEnabled": "WPA3-Personal",
        "SignalNoiseRatio": 0,
        "SignalStrength": -40,
        "SignalStrengthByChain": "-37.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0",
        "SignalStrengthHistory": "-48,0,-39,-41",
        "SupportedHtMCS": "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15",
        "SupportedMCS": "",
        "TxBytes": 12635057,
        "TxErrors": 1,
        "TxMulticastPacketCount": 0,
        "TxPacketCount": 39933,
        "TxSupportedHe160MCS": "11,11",
        "TxSupportedHe80x80MCS": "",
        "TxSupportedHeMCS": "11,11",
        "TxSupportedVhtMCS": "9,9",
        "TxUnicastPacketCount": 0,
        "Tx_Retransmissions": 0,
        "Tx_RetransmissionsFailed": 0,
        "UNIIBandsCapabilities": "U-NII-1,U-NII-2A,U-NII-2C,U-NII-3,U-NII-4,U-NII-5,U-NII-6,U-NII-7,U-NII-8",
        "UplinkBandwidth": 80,
        "UplinkMCS": 11,
        "UplinkRateSpec": "he_11_80_2_800",
        "UplinkShortGuard": 1,
        "VendorCapabilities": "",
        "VendorOUI": "00:50:F2,00:17:35",
        "VhtCapabilities": "SGI80,SGI160,SU-BFE,MU-BFE",
    },
    "Device.WiFi.AccessPoint.1.AssociatedDevice.3.": {
        "Active": 1,
        "AssociationTime": "Tue, 28 Jan 2025 08:49:58 GMT",
        "AuthenticationState": 1,
        "AvgSignalStrength": 0,
        "AvgSignalStrengthByChain": -37,
        "Capabilities": "RRM,BTM,PMF",
        "ChargeableUserId": "",
        "ConnectionDuration": 22412,
        "DevicePriority": 1,
        "DeviceType": "Data",
        "DisassociationTime": "Tue, 28 Jan 2025 08:49:54 GMT",
        "DownlinkBandwidth": 80,
        "DownlinkMCS": 11,
        "DownlinkRateSpec": "he_11_80_2_1600",
        "DownlinkShortGuard": 1,
        "EncryptionMode": "Default",
        "FrequencyCapabilities": "2.4GHz,5GHz,6GHz",
        "HeCapabilities": "SU&MU-BFE",
        "HtCapabilities": "40MHz,SGI20,SGI40",
        "Inactive": 5,
        "LastDataDownlinkRate": 1134200,
        "LastDataUplinkRate": 1200900,
        "LastStateChange": "Tue, 28 Jan 2025 08:49:59 GMT",
        "LinkBandwidth": "80MHz",
        "MACAddress": "66:55:44:33:22:11",
        "MUGroupId": 0,
        "MUMimoTxPktsCount": 0,
        "MUMimoTxPktsPercentage": 0,
        "MUUserPositionId": 0,
        "MaxBandwidthSupported": "160MHz",
        "MaxDownlinkRateReached": 1200900,
        "MaxDownlinkRateSupported": 2401911,
        "MaxRxSpatialStreamsSupported": 2,
        "MaxTxSpatialStreamsSupported": 2,
        "MaxUplinkRateReached": 1200900,
        "MaxUplinkRateSupported": 2401911,
        "Noise": 86,
        "OperatingStandard": "ax",
        "PowerSave": 0,
        "Retransmissions": 0,
        "RrmCapabilities": "NEIGHBOR,BEACON_ACTIVE,BEACON_PASSIVE,BEACON_TABLE",
        "RrmOffChannelMaxDuration": 0,
        "RrmOnChannelMaxDuration": 0,
        "RxBytes": 1972163,
        "RxMulticastPacketCount": 0,
        "RxPacketCount": 15135,
        "RxSupportedHe160MCS": "11,11",
        "RxSupportedHe80x80MCS": "",
        "RxSupportedHeMCS": "11,11",
        "RxSupportedVhtMCS": "9,9",
        "RxUnicastPacketCount": 0,
        "Rx_Retransmissions": 0,
        "Rx_RetransmissionsFailed": 0,
        "SecurityModeEnabled": "WPA3-Personal",
        "SignalNoiseRatio": 0,
        "SignalStrength": -40,
        "SignalStrengthByChain": "-37.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0",
        "SignalStrengthHistory": "-48,0,-39,-41",
        "SupportedHtMCS": "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15",
        "SupportedMCS": "",
        "TxBytes": 12635057,
        "TxErrors": 1,
        "TxMulticastPacketCount": 0,
        "TxPacketCount": 39933,
        "TxSupportedHe160MCS": "11,11",
        "TxSupportedHe80x80MCS": "",
        "TxSupportedHeMCS": "11,11",
        "TxSupportedVhtMCS": "9,9",
        "TxUnicastPacketCount": 0,
        "Tx_Retransmissions": 0,
        "Tx_RetransmissionsFailed": 0,
        "UNIIBandsCapabilities": "U-NII-1,U-NII-2A,U-NII-2C,U-NII-3,U-NII-4,U-NII-5,U-NII-6,U-NII-7,U-NII-8",
        "UplinkBandwidth": 80,
        "UplinkMCS": 11,
        "UplinkRateSpec": "he_11_80_2_800",
        "UplinkShortGuard": 1,
        "VendorCapabilities": "",
        "VendorOUI": "00:50:F2,00:17:35",
        "VhtCapabilities": "SGI80,SGI160,SU-BFE,MU-BFE",
    }
}

